# Generated by Django 5.1.4 on 2025-05-29 07:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=users.models.MediaStorage(), upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
