services:
  - type: web
    name: bestmoment-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn video_feed.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: video_feed.settings.prod
      - key: SECRET_KEY
        value: django-insecure-x8y_=i!z2peu2aid=icb5asf&ruu1=n)4wh1!!k(qv@by8e0@4 
      - key: ALLOWED_HOSTS
        value: bestmoment.onrender.com
      - key: DEBUG
        value: False
